"""
Tool Name: GenerateIncidentReport
Description: Generate a structured incident report from investigation findings.
Produces a formatted markdown report with timeline, root cause, impact, and remediation sections.
Use when asked to create an incident report, post-mortem, or RCA document.

Parameters:
  - incident_title (str): Short title of the incident
  - start_time (str): When the incident started (ISO format or human-readable)
  - end_time (str): When the incident was resolved (ISO format or human-readable)
  - root_cause (str): Description of the root cause
  - impact (str): Description of the impact on users/services
  - remediation (str): What was done to fix the issue
  - severity (str): Incident severity (Sev1, Sev2, Sev3). Default: Sev1
  - lessons_learned (str): Key takeaways. Default: empty
"""

from datetime import datetime

def main(
    incident_title: str,
    start_time: str,
    end_time: str,
    root_cause: str,
    impact: str,
    remediation: str,
    severity: str = "Sev1",
    lessons_learned: str = ""
) -> dict:
    """Generate a structured incident report in markdown format."""

    report_id = f"INC-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    report = f"""# Incident Report: {report_id}

## Summary
| Field | Value |
|-------|-------|
| **Title** | {incident_title} |
| **Severity** | {severity} |
| **Start Time** | {start_time} |
| **End Time** | {end_time} |
| **Report Generated** | {generated_at} |

## Timeline
1. **{start_time}** — Incident began. Initial symptoms detected.
2. **Detection** — Azure Monitor alerts fired. SRE Agent began investigation.
3. **Investigation** — SRE Agent queried Application Insights and Activity Log.
4. **Root Cause Identified** — {root_cause}
5. **{end_time}** — Remediation applied. Service restored.

## Root Cause Analysis
{root_cause}

## Impact
{impact}

## Remediation
{remediation}

## Lessons Learned
{lessons_learned if lessons_learned else "To be completed in post-incident review."}

## Action Items
- [ ] Review alert thresholds for adequacy
- [ ] Update runbooks with findings from this incident
- [ ] Upload this report to SRE Agent knowledge base for future reference
- [ ] Schedule post-incident review meeting

---
*Report generated by SRE Agent Custom Tool — {generated_at}*
"""

    # Write to file system for download
    file_path = f"/mnt/data/{report_id}.md"
    try:
        with open(file_path, "w") as f:
            f.write(report)
        file_available = True
    except Exception:
        file_path = None
        file_available = False

    return {
        "report_id": report_id,
        "report_markdown": report,
        "file_path": file_path,
        "file_available": file_available,
        "generated_at": generated_at
    }
